### ISSUE TITLE
improve pipeline performance

### ISSUE THREAD

**Issue by tgross** [plan-systems/plan-ci#5]
When a full rebuild fires (as it does for merges to `plan-core` or this repo), we end up with some 60+ garden processes running. Although we've got a lot of memory on the box, we only have 4 i5 cores (@2.20GHz) so that's just a lot in terms of load. If we can reduce the number of parallel processes we might have faster individual builds and free up some CPU room for other tasks on the box.

**Comment by tgross** [comment]
I've reduced the number of builds possible per job, but we're really slamming the whole machine with a combination of:

- a large number of parallel checks, each of which fires up a lightweight `git` container (maybe we can leverage the new [global resources](https://concourse-ci.org/global-resources.html) feature here?)
- `go get` is pretty greedy, and we're not re-using it between services. Maybe module vendoring is the best long-term strategy here (the golang community favors this).
- it _seems_ lot of the time is being spent setting up and tearing down containers. I'd want to profile it to be sure, but eyeballing it while sitting here waiting for the console suggests that. I'm not sure what makes this so slow, but we could pretty easily run most of the get/test/lint/build cycle as a Makefile in each application's own repo. I might look into testing this out.

**Comment by drew-512** [comment]
Interesting...  I guess that downside is just more stuff to maintain.

**Comment by tgross** [comment]
>  I guess that downside is just more stuff to maintain.

The flipside of _that_ is we'd be able to assert a little more consistency in the local dev process. If `make` and `make test` work on CI it'll match up directly with what's there in local dev (presumably :grinning: )

**Comment by tgross** [comment]
I've trimmed about 5 min off the time (~1/3rd) with the latest iteration of the pipeline (as of 92ce55e), which consolidates steps into `make check` and `make release` and that results in a _lot_ less churn of container overlay file systems.

This is getting each job down to ~10 min, of which we're spending 4-6 minutes doing `go get` fetches because we're not caching the package directory between `make check` and `make release`.

Examples of the new pipeline:
https://ci.machinistlabs.com/teams/plan/pipelines/plan/jobs/plan-pnode/builds/16
https://ci.machinistlabs.com/teams/plan/pipelines/plan/jobs/plan-pdi-local/builds/15

**Comment by tgross** [comment]
The tricky bit here is that Concourse will only let us cache/output a directory relative to the task workspace, and not an arbitrary location like `~/go`.

This post https://www.orsolabs.com/post/building-go-code-with-concourse/ has some discussion of how we might be able to take a crack at caching the go pkg directory by setting `GOPATH` (even though we're using modules and don't normally need it) so that the packages get dropped somewhere that Concourse will let us cache them.

**Comment by tgross** [comment]
Ok, I've now got caching of the go pkg directory working as of 193fa9a1ece52db8727f605c56a4efb4a7d49b20

That knocks the `make release` step down to only a few _seconds_, which is exactly what I was hoping for: https://ci.machinistlabs.com/teams/plan/pipelines/plan/jobs/plan-pnode/builds/19

This has taken jobs down from ~15 min to 3-4 min. I'm satisfied with these results for the time being. We can revisit in the future if we feel like build times are creeping back up again.

**Comment by drew-512** [comment]
nice!
